name: Deploy to Azure
on:
  push:
    branches:
      - main

jobs:
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Azure Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push API
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.IMAGE_API_REPOSITORY }}:latest

      - name: Build and push Queue Listener
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./queue-listener/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.IMAGE_QUEUE_LISTENER_REPOSITORY }}:latest

  redeploy:
    name: Redeploy to Azure
    needs: build-images
    runs-on: ubuntu-24.04

    steps:
      - name: 'Deploy API'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ vars.APP_NAME }}
          dns-name-label: ${{ vars.APP_NAME }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.IMAGE_API_REPOSITORY }}:latest
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: ${{ vars.APP_NAME }}api
          location: ${{ vars.REGION }}

      - name: 'Deploy Queue Listener'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ vars.APP_NAME }}
          dns-name-label: ${{ vars.APP_NAME }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.IMAGE_QUEUE_LISTENER_REPOSITORY }}:latest
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: ${{ vars.APP_NAME }}api
          location: ${{ vars.REGION }}
